#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Adapted from https://gist.github.com/vlucas/8009a5edadf8d0ff7430
protected_branch='master'
policy="\n\n[Policy] Never push code directly to the \"$protected_branch\" branch! (Prevented with pre-push hook.)\n\n"
current_branch=$(git branch --show-current)

do_exit(){
  echo -e $policy
  exit 1
}

if [ $current_branch = $protected_branch ]; then
  do_exit
fi
unset do_exit
exit 0
